name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # Install any dependencies your project needs
        # For example, npm install, pip install, etc.
        echo "Install dependencies here"

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USERNAME }}
        key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
        script: |
          # Commands to deploy your code on the EC2 instance
          # For example:
          # cd /path/to/your/project
          git pull origin main
          # Any other deployment commands

